### ISSUE TITLE
negative Temperatures on x-axis missing in saved plots

### ISSUE THREAD

**Issue by peters77** [aperezhortal/SkewTplus#3]
Andres, 

next problem: 
no negative Temps on x-xaxis:

Code: 

```
# If no X server is available to visualize the plot, save it to file
import matplotlib
matplotlib.use('Agg')
from SkewTplus.sounding import sounding

#Load the sounding datas
#mySounding = sounding("./sounding.txt")

#Load the sounding data
mySounding = sounding("20190111:00",fileFormat='web', stationId= "ETGI")

# Save the SkewT diagram of the Sounding
mySounding.quickPlot(output_file="quick_sounding.pdf")
```

Output: 

![bildschirmfoto 2019-01-11 um 23 20 16](https://user-images.githubusercontent.com/8840918/51062537-868cf180-15f7-11e9-8aad-76f15b68cfd3.png)

Same with `mySkewT_Figure.save_fig` or writing to .png

**Comment by aperezhortal** [comment]
The Figure was not being updated before saving/showing the plot. 
FIxed in  afad4ec.
